export const photos = [
    {
        src:"/photos/1.jpg",
        alt:"nature-Image",
    },
    {
        src:"/photos/2.jpg",
        alt:"nature-Image",
    },
    {
        src:"/photos/3.jpg",
        alt:"nature-Image",
    },
    {
        src:"/photos/4.jpg",
        alt:"nature-Image",
    },
    {
        src:"/photos/5.jpg",
        alt:"nature-Image",
    },
    {
        src:"/photos/6.jpg",
        alt:"nature-Image",
    },
    {
        src:"/photos/7.jpg",
        alt:"nature-Image",
    },
    {
        src:"/photos/8.jpg",
        alt:"nature-Image",
    },
    {
        src:"/photos/9.jpg",
        alt:"nature-Image",
    },
    {
        src:"/photos/10.jpg",
        alt:"nature-Image",
    },
    {
        src:"/photos/11.jpg",
        alt:"nature-Image",
    },
    {
        src:"/photos/12.jpg",
        alt:"nature-Image",
    },
    {
        src:"/photos/13.jpg",
        alt:"nature-Image",
    },

]